version: 2.0
jobs:
  build:
    docker:
      - image: centos:7
    steps:
      - checkout
      - run: ci/setup.sh
      - run: ci/build.sh
   
  deploy:
    docker:
      - image: centos:7
    steps:
      - run: ci/deploy.sh

